name: http_certificate_pinning_example
description: Demonstrates how to use the http_certificate_pinning plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  http_certificate_pinning:
    path: ../

flutter:
  uses-material-design: true